### ISSUE TITLE
desired accuracy option and its default value

### ISSUE THREAD

**Issue by MrFreeDragon** [JeanLucPons/Kangaroo#12]
Hi!

Is it possible to add the desired accuracy option and also set its default value in the program? Accuracy could be set in probability %% (for example 75%) or in deviation from the average expected operations (for example +30% for the expected average range). If the desired acuuracy met the program stops and say that the key was not found.

The issue is the program will work forever if the input range was wrong. Even the program made the whole range operations, it will not stop.

Here is the short example:

I used the 2^33 range and the public key as the input:
3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f9416c84a01e
3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f94276067b89
04ac94fc802939963cab6818b890448c756ab5b44b523a9e90e65c48f87a3244df0748a7c458de0b0162a4b0848a0d856f2abb07557b0bbe5791156d4258ff9253

However the actual range was edited (instead or real range 4d2351... I used 3d2351... - changed the 1st letter from 4 to 3), so the 2^33 range was not correct.

This was the result of the program:
Kangaroo v1.3
Start:3D2351DAFAF9B1B4DD11E2AE87C6E5D4007100F36AFD1740A885F9416C84A01E
Stop :3D2351DAFAF9B1B4DD11E2AE87C6E5D4007100F36AFD1740A885F94276067B89
Keys :1
Number of CPU thread: 0
Range width: 2^33
Number of random walk: 2^20.81 (Max DP=0)
DP size: 0 [0x0]
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(56x256) (177.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^20.81 kangaroos in 5439.5ms

Warning, 29229056 items lost
Hint: Search with less threads (-g)
[31.41 MKey/s][GPU 31.41 MKey/s][Count 2^33.25][Dead 1876287][03:46][3348.0MB]

We see that even the range length was 2^33, the program performed 2^33.25 operations... but it continued to work and kill kangaroos.... (almost 1.9 millions kangaroos were killed).

**Comment by RB61** [comment]
> 16c84a01e

Hi
Have you tried this example with CPU only ?  if so, what do you get?

**Comment by CatfishCrypt** [comment]
For the 2^33 range, less than 2 seconds.

**Comment by RB61** [comment]
> For the 2^33 range, less than 2 seconds.

That's what I figured. From what I understand is that tame Kangaroos hop and stays within the initial range while wild ones will eventually hop out of the range (I suppose that's the dead Kangaroos). Now, if initial range is small, you don't need gpu and so many threads... Somehow you start with too many kagaroos and the algorithm probably runs in some issues that I am sure Jean Luc will explain much better than me ;).

**Comment by MrFreeDragon** [comment]
**CatfishCrypt**, **RB61**, the reason of this is not to solve the key. I told that the range was wrong intentionally. The program never solve the key as it is out of range.

Tty to solve this. You will not find the answer. And the program will work, work and work:
3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f9416c84a01e
3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f94276067b89
04ac94fc802939963cab6818b890448c756ab5b44b523a9e90e65c48f87a3244df0748a7c458de0b0162a4b0848a0d856f2abb07557b0bbe5791156d4258ff9253

But iif you input the correct range it will solve the key for some seconds:
4d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f9416c84a01e
4d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f94276067b89
04ac94fc802939963cab6818b890448c756ab5b44b523a9e90e65c48f87a3244df0748a7c458de0b0162a4b0848a0d856f2abb07557b0bbe5791156d4258ff9253

So my point is to add to the program the desited accuracy. For example, with Pollard Kangaroo method for 2^33 range it is enough to perform in average 2*sqrt(2^33) = 2^17.5 operations to solve the key. I set the accuracy let's say 2^22 operations. So if the program perform 2^22 operations it stops and does not continue solving. Otherwise it will work forever....
For 2^33 range it is easy, as the whole range could be checked very quickly. But for larger ranges it could be important.

**Comment by RB61** [comment]
> **CatfishCrypt**, **RB61**, the reason of this is not to solve the key. I told that the range was wrong intentionally. The program never solve the key as it is out of range.
> 
> Tty to solve this. You will not find the answer. And the program will work, work and work:
> 3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f9416c84a01e
> 3d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f94276067b89
> 04ac94fc802939963cab6818b890448c756ab5b44b523a9e90e65c48f87a3244df0748a7c458de0b0162a4b0848a0d856f2abb07557b0bbe5791156d4258ff9253
> 
> But iif you input the correct range it will solve the key for some seconds:
> 4d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f9416c84a01e
> 4d2351dafaf9b1b4dd11e2ae87c6e5d4007100f36afd1740a885f94276067b89
> 04ac94fc802939963cab6818b890448c756ab5b44b523a9e90e65c48f87a3244df0748a7c458de0b0162a4b0848a0d856f2abb07557b0bbe5791156d4258ff9253
> 
> So my point is to add to the program the desited accuracy. For example, with Pollard Kangaroo method for 2^33 range it is enough to perform in average 2*sqrt(2^33) = 2^17.5 operations to solve the key. I set the accuracy let's say 2^22 operations. So if the program perform 2^22 operations it stops and does not continue solving. Otherwise it will work forever....
> For 2^33 range it is easy, as the whole range could be checked very quickly. But for larger ranges it could be important.

Ooops ... I missed out the part where you say that you start with an incorrect range. 
ok. now I get your point.

**Comment by kpot87** [comment]
The same when the speed of GPU or CPU decrease to 0

**Comment by kpot87** [comment]
Any body have to find solution about range of search?

**Comment by CatfishCrypt** [comment]
@MrFreeDragon I understood your point/intent. I was answering a question by RB61.  What do you think about making it read the number of "dead" kangaroos and after so many, the program terminates/moves to the next range? In all ranges that I've tested, medium sized up to 2^90, the dead kangaroo numbers have been small, less than 20. I do agree that it definitely should stop if operations exceed the range.

**Comment by JeanLucPons** [comment]
Hi,
Yes I think a stop option could be useful as MrFreeDragon said depending on the expected number of operation. The problem with dead kangaroo is that it depends where the key you search lies in the range.

**Comment by JeanLucPons** [comment]
done in 1.4
