### ISSUE TITLE
Finding Public key

### ISSUE THREAD

**Issue by learnercrypto** [JeanLucPons/Kangaroo#133]
Can you please tell me public key of this address

1FvUkW8thcqG6HP7gAvAjcR52fR7CYodBx

**Comment by marssystems** [comment]
No public key for this address 1FvUkW8thcqG6HP7gAvAjcR52fR7CYodBx, as it doesn't have any outgoing transactions - yet.

**Comment by learnercrypto** [comment]
It does have outgoing transaction.

Total Sent
400.00000000 BTC
$39,124,720

**Comment by marssystems** [comment]
If that is the case, you should be able to derive the pubkey by analysing the transaction data.

**Comment by learnercrypto** [comment]
Where to look?

scriptPubKey (asm)
OP_PUSHBYTES_65 0497c03a78e134e617c94f0410c5e0088ec335074659c59ef7bd27732dbf6149708c2d0aed5f2a226ea826da69cc2c7e2861df4614b895d8037444775c9f60a727 OP_CHECKSIG
scriptPubKey (hex)
410497c03a78e134e617c94f0410c5e0088ec335074659c59ef7bd27732dbf6149708c2d0aed5f2a226ea826da69cc2c7e2861df4614b895d8037444775c9f60a727ac
Spending tx
Spent by [1f5f5cdc240736df21afdf18983bf4fb3818486b0110979dacde7a9b1019850f:0](https://blockstream.info/tx/1f5f5cdc240736df21afdf18983bf4fb3818486b0110979dacde7a9b1019850f?input:0) in block [#75034](https://blockstream.info/block/000000000015ecc1aba8e6de9176cbece63d8ee2e126c53a8d8b4e807e86c18c)

**Comment by marssystems** [comment]
Try this pubkey  -  040b8a0382802e12fc345e9bace8b99f6aed6b90fbfd796e8027ca9bb5f472778db863952bdb6e9e399e34f941cab2fa6c244e65af2d15244fee2d795b3f6e222d

**Comment by marssystems** [comment]
You can try the compressed version of the key  -  030b8a0382802e12fc345e9bace8b99f6aed6b90fbfd796e8027ca9bb5f472778d
