### ISSUE TITLE
1.4gamma

### ISSUE THREAD

**Issue by hamnaz** [JeanLucPons/Kangaroo#17]
./kangaroo -t 0 -gpu in.txt
Kangaroo v1.4gamma
Start:0
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 0
Range width: 2^56
Jump Avg distance: 2^26.99
Number of kangaroos: 2^17.39
Suggested DP: 10
Expected operations: 2^29.45
Expected RAM: 55.7MB
DP size: 10 [0xffc0000000000000]
GPU: GPU #0 GeForce GTX 460 (7x48 cores) Grid(14x96) (24.8 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^17.39 kangaroos in 810.0ms
[28.24 MK/s][GPU 28.24 MK/s][Count 2^33.57][Dead 271][08:35 (Avg 25s)][953.7MB]  ^C

not solved

**Comment by hamnaz** [comment]
./kangaroo -t 0 -d 5 -gpu in.txt
Kangaroo v1.4gamma
Start:0
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 0
Range width: 2^56
Jump Avg distance: 2^26.98
Number of kangaroos: 2^17.39
Suggested DP: 10
Expected operations: 2^29.07
Expected RAM: 1343.1MB
DP size: 5 [0xf800000000000000]
GPU: GPU #0 GeForce GTX 460 (7x48 cores) Grid(14x96) (24.8 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^17.39 kangaroos in 803.1ms
[7.30 MK/s][GPU 7.30 MK/s][Count 2^31.38][Dead 17][03:38 (Avg 01:17)][6659.5MB]  Killed

**Comment by CatfishCrypt** [comment]
I had similiar results. I think JPL is tweaking the code everyday. I did run a 40 bit test and it solved/found it, but when I went up to 56 and 64, it just kept going. Try a 40 bit test and see if you find it.

**Comment by hamnaz** [comment]
nt 2^34.44][Dead 35][15:40 (Avg 01:46:01)][4.8MB]  ^C
chawla@i3-6100:~/jean/Kangaroo$ ./kangaroo in.txt
Kangaroo v1.4gamma
Start:0
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 4
Range width: 2^56
Jump Avg distance: 2^27.05
Number of kangaroos: 2^12.00
Suggested DP: 16
Expected operations: 2^29.62
Expected RAM: 2.0MB
DP size: 16 [0xffff000000000000]
SolveKeyCPU Thread 2: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
[12.83 MK/s][GPU 0.00 MK/s][Count 2^33.60][Dead 152][19:19 (Avg 01:04)][22.2MB]

cpu test failed too

**Comment by JeanLucPons** [comment]
Hi,
These release is still in dev.
I tried symmetry optimization but it is not really possible on large range.
Wait the next official release or get a stable one.

**Comment by CatfishCrypt** [comment]
I've ran it several times, cpu and gpu, works well for 72 range and below.  haven't tried it above that. It seems it takes a little longer than suggested time and RAM. CPU only seems faster for lower ranges.
