### ISSUE TITLE
-r walks

### ISSUE THREAD

**Issue by CatfishCrypt** [JeanLucPons/Kangaroo#18]
Jean Luc,

Have you read studies/papers/experiments on the -r walking that can be used with Kangaroo? Seems interesting.

**Comment by JeanLucPons** [comment]
Hi,
No, what is "-r walks" ? r-adding walks ? Could you give me some links ?
Thanks ;)

**Comment by CatfishCrypt** [comment]
I guess it was more for the various "parallelization" methods, versus the Kangaroo/Lambda.
