### ISSUE TITLE
Herds - add more?

### ISSUE THREAD

**Issue by CatfishCrypt** [JeanLucPons/Kangaroo#19]
Jean Luc,

If I wanted to add more herds (evenly) between wild and tame herds, where would I do this in the code? Basically, if currently there is 1 tame and 1 wild herd, how would I make 2 tame and 2 wild herds and create different starting points for each?

**Comment by JeanLucPons** [comment]
Hi,
A herd is a set of kangaroo starting each of them at a random point in the range.
