### ISSUE TITLE
GPU issue

### ISSUE THREAD

**Issue by hamnaz** [JeanLucPons/Kangaroo#2]
simply gpu heat shown from 42c to 65c, gpu ram 0 used, gpu core 0 used
speed seems app useing cpu cores and finsih

./kangaroo in.txt
Kangaroo v1.0
Start:0
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 4
Range width: 2^56
Number of random walk: 2^12.00 (Max DP=14)
DP size: 14 [0xfffc000000000000]
SolveKeyCPU Thread 2: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
[6.18 MKey/s][GPU 0.00 MKey/s][Count 2^29.26][Dead 4][01:59][7.3MB]
Key# 0 Pub:  0x02E9F43F810784FF1E91D8BC7C4FF06BFEE935DA71D7350734C3472FE305FEF82A
       Priv: 0x378ABDEC51BC5D

**Comment by JeanLucPons** [comment]
Wait it is in dev
You need to add -gpu to enable

**Comment by virus-cyber** [comment]
Kangaroo.exe -t 0 -g 28,256 -gpu -gpuId 0 in.txt

**Comment by hamnaz** [comment]
you mean compile with make -gpu ?

**Comment by JeanLucPons** [comment]
no like virus said
for compile as usual in my project:
make ccap=yourccap gpu=1 all

**Comment by hamnaz** [comment]
i will sugguest you, always mark 2 section in readme 
1. compile
method of compile commands
2. run
methode of run commands

it will help new and old users to always read readme and follow
thankx

**Comment by JeanLucPons** [comment]
Very fisrt result on my GTX 1050 Ti, 64bit key solved in 2min !
```
C:\C++\Kangaroo\VC_CUDA10\x64\Release>Kangaroo.exe -t 0 -gpu ..\..\in.txt
Kangaroo v1.0
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EFFFFFFFFFFFFFFFF
Keys :16
Number of CPU thread: 0
Range width: 2^64
Number of random walk: 2^18.58 (Max DP=11)
DP size: 11 [0xFFE0000000000000]
GPU: GPU #0 GeForce GTX 1050 Ti (6x128 cores) Grid(12x256) (45.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^18.58 kangaroos
[115.23 MKey/s][GPU 115.23 MKey/s][Count 2^33.52][Dead 5][02:02][463.9MB]
Key# 0 Pub:  0x0259A3BFDAD718C9D3FAC7C187F1139F0815AC5D923910D516E186AFDA28B221DC
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EBB3EF3883C1866D4
```

**Comment by JeanLucPons** [comment]
Yes I update the README asap :)

**Comment by hamnaz** [comment]
in my first run, gpu and cpu all uses at same time

./kangaroo -gpu in.txt
Kangaroo v1.0
Start:8000000000000000000000001
Stop :FFFFFFFFFFFFFFFFFFFFFFFFE
Keys :2048
Number of CPU thread: 4
Range width: 2^99
Number of random walk: 2^17.43 (Max DP=30)
DP size: 30 [0xfffffffc00000000]
SolveKeyCPU Thread 2: 1024 kangaroos
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
GPU: GPU #0 GeForce GTX 460 (7x48 cores) Grid(14x96) (24.8 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyGPU Thread GPU#0: 2^17.39 kangaroos
[38.03 MKey/s][GPU 25.72 MKey/s][Count 2^32.97][Dead 0][04:21][1.0MB]

**Comment by hamnaz** [comment]
cpu ver
only cpu speed is 11.34 mkeys/s
gpu ver
[38.03 MKey/s][GPU 25.72 MKey/s][Count 2^32.97][Dead 0][04:21][1.0MB]

mean 25.72 mkeys/s at gpu

**Comment by virus-cyber** [comment]
Kangaroo v1.0
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EFFFFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 0
Range width: 2^64
Number of random walk: 2^19.81 (Max DP=10)
DP size: 10 [0xFFC0000000000000]
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^19.81 kangaroos
[254.34 MKey/s][GPU 254.34 MKey/s][Count 2^32.85][Dead 1][33s][582.8MB]
Key# 0 Pub:  0x0259A3BFDAD718C9D3FAC7C187F1139F0815AC5D923910D516E186AFDA28B221DC
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EBB3EF3883C1866D4

Done: Total time 45s

**Comment by JeanLucPons** [comment]
That is not so bad for a very first release :)

**Comment by hamnaz** [comment]
by setting grid 64,128 now i am getting 50 Mkeys/s

**Comment by hamnaz** [comment]
i think next task is multiple pubkeys check :)

**Comment by JeanLucPons** [comment]
Yes I will optimize thing for multiple key.
There is a great optimization that can be done by resuing old points.

**Comment by virus-cyber** [comment]
Kangaroo v1.0
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EFFFFFFFFFFFFFFFF
Keys :16
Number of CPU thread: 0
Range width: 2^64
Number of random walk: 2^19.81 (Max DP=10)
DP size: 10 [0xFFC0000000000000]
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^19.81 kangaroos
[264.38 MKey/s][GPU 264.38 MKey/s][Count 2^32.29][Dead 1][22s][395.9MB]
Key# 0 Pub:  0x0259A3BFDAD718C9D3FAC7C187F1139F0815AC5D923910D516E186AFDA28B221DC
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EBB3EF3883C1866D4
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[230.06 MKey/s][GPU 230.06 MKey/s][Count 2^34.01][Dead 4][01:29][1294.6MB]
Key# 1 Pub:  0x02A50FBBB20757CC0E9C41C49DD9DF261646EE7936272F3F68C740C9DA50D42BCD
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EB5ABC43BEBAD3207
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[246.17 MKey/s][GPU 246.17 MKey/s][Count 2^33.20][Dead 0][52s][741.5MB]
Key# 2 Pub:  0x0304A49211C0FE07C9F7C94695996F8826E09545375A3CF9677F2D780A3EB70DE3
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E5698AAAB6CAC52B3
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[257.74 MKey/s][GPU 257.74 MKey/s][Count 2^32.46][Dead 1][34s][444.9MB]
Key# 3 Pub:  0x030B39E3F26AF294502A5BE708BB87AEDD9F895868011E60C1D2ABFCA202CD7A4D
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E59C839258C2AD7A0
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[233.83 MKey/s][GPU 233.83 MKey/s][Count 2^33.75][Dead 1][01:15][1078.4MB]
Key# 4 Pub:  0x02837A31977A73A630C436E680915934A58B8C76EB9B57A42C3C717689BE8C0493
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E765FB411E63B92B9
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[244.59 MKey/s][GPU 244.59 MKey/s][Count 2^33.03][Dead 3][48s][658.7MB]
Key# 5 Pub:  0x020ECDB6359D41D2FD37628C718DDA9BE30E65801A88A00C3C5BDF36E7EE6ADBBA
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E7D0E6081C7E0E865
GPU: GPU #0 GeForce GTX 1080 Ti (28x128 cores) Grid(28x256) (93.0 MB used)
[225.58 MKey/s][GPU 225.58 MKey/s][Count 2^34.15][Dead 4][01:39][1424.9MB]
Key# 6 Pub:  0x0322DD52FCFA3A4384F0AFF199D019E481D335923D8C00BADAD42FFFC80AF8FCF0
       Priv: 0x49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EC737344CA673CE28

**Comment by djarumlights** [comment]
JLP at it again with the excellence!

**Comment by kpot87** [comment]
> 
> 
> Yes I will optimize thing for multiple key.
> There is a great optimization that can be done by resuing old points.

Hi the question is how you choose range where to search keys? why you choose in the readme this Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EFFFFFFFFFFFFFFFF
for you pubkeys? how you choose range? Thanks

**Comment by JeanLucPons** [comment]
@kpot87 
I will write few words to explain this on the README today.

**Comment by kpot87** [comment]
SolveKeyGPU Thread GPU#0: 2^21.69 kangaroos in 12984.0ms
[858.15 MKey/s][GPU 858.15 MKey/s][Count 2^46.52][Dead 0][1.6d][464.9MB]  B]

Hi! what does it mean "B" at the end?

**Comment by JeanLucPons** [comment]
It is the last B] of  MB], line is not cleared, a printing bug ;)

**Comment by Shadow145-cpu** [comment]
Hi, Low speed with GTX1060 6GB
It is normal speed or something wrong?
