### ISSUE TITLE
RAM / Memory / Storage

### ISSUE THREAD

**Issue by CatfishCrypt** [JeanLucPons/Kangaroo#20]
So program currently uses RAM. I know that RAM is faster than say SSD or HD. Why can't the DP/hashtable be written to a space on SSD and checked so many minutes for collision or just let it be slower than the current RAM way? I wouldn't care if I had to wait 30 minutes, an hour, 2 hours, etc to verify if a collision has been made, if I could increase the storage requirement by using SSD/HD.

Not possible? Am I missing something?

**Comment by JeanLucPons** [comment]
Yes this can be done.
At the moment, you can save work files, restart a search from scratch and then merge works files.
This is not yet automated.

**Comment by JeanLucPons** [comment]
Will come soon in a client/server release.
I close
