### ISSUE TITLE
Skipe pubkey in given period

### ISSUE THREAD

**Issue by celero1** [JeanLucPons/Kangaroo#21]
Hi Jean Luc pont,
How to skipe pubkeys in a given period ex: I do the 40 bit test with 1000 pubkey, if the result of the first address is not found in a given period (1min max) is it possible to go to the address next and so on for all the pubkeys on the list.

Then how to save in a txt file if the result is found.

For these two subjects if there is a code to do it I would like to have it (skipe and passed to the following address in a given period then  save the result in a txt file) I would also like to know which section to modify to add the code (I'm not a developer) thanks.

**Comment by CatfishCrypt** [comment]
@celero1 

I made a way to save result to a text file.
// Key solved
::printf("\nKey#%2d Pub: 0x%s \n",keyIdx,secp->GetPublicKeyHex(true,P).c_str());
::printf(" Priv: 0x%s \n",pk.GetBase16().c_str());
ofstream myfile;
myfile.open("keyz.txt", ios::out);
myfile << pk.GetBase16().c_str();
myfile.close();
endOfSearch = true;

I added the:
ofstream myfile;
myfile.open("keyz.txt", ios::out);
myfile << pk.GetBase16().c_str();
myfile.close();

to, I believe, the Vanity.cpp code. It's in 4 different places, 2 for CPU and 2 for GPU.

For the "kill" option you spoke of...I'm not sure but I think Jean Luc was going to work on that with a lot of other things, like the output text file as well.

**Comment by celero1** [comment]
@CatfishCrccp Thank you, the part to modify is in kangaroo.ccp code from line 400.

**Comment by JeanLucPons** [comment]
Hi,
The maxstep is not yet fully implemented.
Will come soon.

**Comment by CatfishCrypt** [comment]
@celero1 
you are welcome. You can change the ios::out to ios:app; doing that will allow it to append to the document and not overwrite anything already written to the document.

**Comment by JeanLucPons** [comment]
I'll add an option to write solved key to output file.
maxStep option is now available
