### ISSUE TITLE
Problem with save.work file 

### ISSUE THREAD

**Issue by Coinpiet** [JeanLucPons/Kangaroo#23]
Hello i started Kangaroo with the 80 bit in.txt problem is i want to save every 10 sec and i tryed bevor with every 30 sec but sometimes it comes an time out for save.work.

and speed is not constant it decrease after time out 

here is command:

Kangaroo.exe -t 0 -gpu -gpuId 0,1,2,3,4,5 -ws -w save.work -wi 10 in.txt
Kangaroo v1.4
Start:25FEEE926526B0B4F0085358DF14702F7F6F04E8EC2200000000000000000000
Stop :25FEEE926526B0B4F0085358DF14702F7F6F04E8EC22FFFFFFFFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 0
Range width: 2^80
Jump Avg distance: 2^40.03
Number of kangaroos: 2^22.49
Suggested DP: 17
Expected operations: 2^41.47
Expected RAM: 901.5MB
DP size: 17 [0xFFFF800000000000]
GPU: GPU #0 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
GPU: GPU #2 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#2: creating kangaroos...
GPU: GPU #1 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#1: creating kangaroos...
GPU: GPU #4 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#4: creating kangaroos...
GPU: GPU #5 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#5: creating kangaroos...
GPU: GPU #3 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#3: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^19.91 kangaroos [11.6s]
SolveKeyGPU Thread GPU#2: 2^19.91 kangaroos [11.6s]
SolveKeyGPU Thread GPU#4: 2^19.91 kangaroos [11.8s]
SolveKeyGPU Thread GPU#1: 2^19.91 kangaroos [15.5s]
SolveKeyGPU Thread GPU#5: 2^19.91 kangaroos [11.4s]
SolveKeyGPU Thread GPU#3: 2^19.91 kangaroos [11.1s]
[2894.72 MK/s][GPU 1743.13 MK/s][Count 2^32.75][Dead 0][02s (Avg 17:35)][3.7/11.7MB]
SaveWork timweout !
[1259.27 MK/s][GPU 779.44 MK/s][Count 2^32.86][Dead 0][12s (Avg 40:27)][3.8/12.3MB]
SaveWork: save.work..............................done [543.8 MB] [02s] Fri May  8 18:14:20 2020
[1209.22 MK/s][GPU 1009.52 MK/s][Count 2^34.28][Dead 0][23s (Avg 42:07)][6.8/23.3MB]
SaveWork timweout !
[659.89 MK/s][GPU 657.25 MK/s][Count 2^34.31][Dead 0][33s (Avg 01:17:11)][7.0/23.7MB]
SaveWork timweout !
[561.03 MK/s][GPU 561.02 MK/s][Count 2^34.35][Dead 0][43s (Avg 01:30:47)][7.1/24.1MB]
SaveWork timweout !
[59.70 MK/s][GPU 59.70 MK/s][Count 2^34.39][Dead 0][56s (Avg 14:13:15)][7.2/24.6MB]
SaveWork: save.work..............................done [547.2 MB] [02s] Fri May  8 18:15:04 2020
[617.18 MK/s][GPU 617.18 MK/s][Count 2^35.04][Dead 0][01:06 (Avg 01:22:32)][10.2/32.7MB]
SaveWork timweout !
[652.92 MK/s][GPU 652.92 MK/s][Count 2^35.06][Dead 0][01:13 (Avg 01:18:00)][10.3/33.0MB]

**Comment by CatfishCrypt** [comment]
remove the -ws
I think when that option is used and you are trying to save 
SolveKeyGPU Thread GPU#0: 2^19.91 kangaroos [11.6s]
SolveKeyGPU Thread GPU#2: 2^19.91 kangaroos [11.6s]
SolveKeyGPU Thread GPU#4: 2^19.91 kangaroos [11.8s]
SolveKeyGPU Thread GPU#1: 2^19.91 kangaroos [15.5s]
SolveKeyGPU Thread GPU#5: 2^19.91 kangaroos [11.4s]
SolveKeyGPU Thread GPU#3: 2^19.91 kangaroos [11.1s]

that many kangaroos, it either has to stop/slow down to figure out each kangaroo or their position,

I'm sure Jean Luc can provide better answer. But if you remove the -ws; you won't get the SaveWork timeout.

**Comment by JeanLucPons** [comment]
HI,
Thanks for the report, I will increase the timeout which is 1 second.
Backup.cpp:204  int timeout = 1000;
During the backup all GPU are waiting because the central table is locked, so the key rate will slow down.

**Comment by JeanLucPons** [comment]
I'll increase the timeout in the next release
I close
