### ISSUE TITLE
RAM usage question

### ISSUE THREAD

**Issue by djarumlights** [JeanLucPons/Kangaroo#3]
When checking a range (say a smaller one like 1000000000000000:AFFFFFFFFFFFFFFF which is a 64 bit) and no result found, at what point will the program give up and move onto the next in list? I was seeing well above 6GB RAM with multiple "dead". Is it going to go thru however much RAM is free or is there a point where the program will say "nah, we're done here. Nothing to see. What's next?"

I suppose I'm thinking of in Telariust's CPU Kangaroo program, where you could pretty much tell when it was approaching hashtable overflow.

**Comment by JeanLucPons** [comment]
Hi,
When you have too much threads (a large grid size) and to you try to attack a small range, you face an overhead due to the DP method. So try to decrease the grid size or increase the dpSize using the -d option. 
I will write few things on this in the README today.

**Comment by djarumlights** [comment]
Sounds good. I noticed that when it crossed the threshold of VRAM it seemed to transition over to my system RAM. Not sure if that's intentional or not. When this happens, the overall speed begins to drop as well. 

But basically, stick with the larger ranges, eh? ;)

**Comment by JeanLucPons** [comment]
Memory usage improvement has been done on 1.4
Suggested DP is not yet optimal, tune it manually according to the RAM you want to use.
Open a new issue if you find something wrong.
Thanks;)
