### ISSUE TITLE
How to convert bitcoin address into format acceptable by in.txt

### ISSUE THREAD

**Issue by rvrsh3ll** [JeanLucPons/Kangaroo#37]
How can I convert a bitcoin address into the hex public key to put in my input file?

Preferably in python.

**Comment by JeanLucPons** [comment]
Hi,
You cannot, the address is a hash of the public key, this is a one way transformation.

**Comment by rvrsh3ll** [comment]
Ok, how do we get the target key in the in.txt file then

**Comment by JeanLucPons** [comment]
if you want the corresponding public key of an existing address in the blockchain you can get it only if this address has already send funds.
Ex:  This address [12JzYkkN76xkwvcPT6AWKZtGX6w2LAgsJg](https://www.blockchain.com/btc/address/12JzYkkN76xkwvcPT6AWKZtGX6w2LAgsJg) has an output of 0.00001BTC where you can find the pubkey:
https://www.blockchain.com/btc/tx/17e4e323cfbc68d7f0071cad09364e8193eedf8fefbcbd8a21b4b65717a4b3d3?page=2
0309976ba5570966bf889196b7fdf5a0f9a1e9ab340556ec29f8bb60599616167d

**Comment by rvrsh3ll** [comment]
Thanks!
