### ISSUE TITLE
Convert to hex

### ISSUE THREAD

**Issue by roi35** [JeanLucPons/Kangaroo#4]
Hello, how to convert the address to the right one for work? you can make sure that -bits 120 parameters are loaded, for example, and that you would re-arrange the usual address to 1 in the desired hex address

**Comment by kpot87** [comment]
You must find public key of that address, lock at blockchain, in spend transaction

**Comment by roi35** [comment]
0000000000000000000000000000000000000000000000000000000000000001           1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH       0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798      I still can not understand how to get the latter?

**Comment by JeanLucPons** [comment]
Hi,
This program does not deal with address (1F1tAaz5x1HUXrCNLbtMDqcw6o5GNn4xqX) but with pubkey. As said by kpot87, you need to find the pubkey (if exposed in a spend tx).
If you don't have any information on the pubkey, you will have to specify a full range:
0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
And it will not be solvable in a reasonable time unless you are very very very lucky ;)

**Comment by roi35** [comment]
I apologize for my indiscretion, with the range I understood. but how to register the addresses I need if I have them in the usual format, they start at 1 ... does it work in any way?

**Comment by JeanLucPons** [comment]
> I apologize for my indiscretion, with the range I understood. but how to register the addresses I need if I have them in the usual format, they start at 1 ... does it work in any way?

If you want to solve this address: 1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH which correspond to
0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 
If you don't know the range:
then you in.txt should look like:
```
0
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 
```
But this will be unsolvable....

**Comment by larocfra** [comment]
How did you get that address 0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798 from that 1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH  ???

**Comment by JeanLucPons** [comment]
Here:
https://www.blockchain.com/btc/tx/099f7953209894ff99d84f1d4ea1afbcaff7572cab66934eb2b2102b69ff6aee

**Comment by larocfra** [comment]
Got it, now how to you calculate an average range for the privkey ? in the demo you show 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000
49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5effffffffffffffff 

Where did you get that range

**Comment by futuremoneybtc** [comment]
@larocfra  you can get any public key of addresses through this [quarry](https://blockchain.info/q/pubkeyaddr/1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH) just put the address you want to get the public key.

**Comment by kpot87** [comment]
> @larocfra you can get any public key of addresses through this [quarry](https://blockchain.info/q/pubkeyaddr/1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH) just put the address you want to get the public key.

But this is to get pubkey not range of search

**Comment by larocfra** [comment]
That I know already, so for the range of search it is pure luck or you have any idea how to generate a search range for the privkey base on the public key.

**Comment by kpot87** [comment]
> That I know already, so for the range of search it is pure luck or you have any idea how to generate a search range for the privkey base on the public key.

No, for now I don’t have result how to find by pubkey range of search for private key, but I am working on it, maybe it can be done never) As I know to 2^60 nothing to search (all taken before:) some one told to 2^80. But for range that took JLP 49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5e0000000000000000
49dccfd96dc5df56487436f5a1b18c4f5d34f65ddb48cb5effffffffffffffff
For address 1BgGZ9tcN4rm9KBzDn7KprQz87SZ26SAMH
I haven’t found any were, I know this address of reuse R value and possible to recover private key, but not range, maybe he know more of us...
