### ISSUE TITLE
GPUEngine

### ISSUE THREAD

**Issue by g00dwin555** [JeanLucPons/Kangaroo#40]
Hello.
An error appears on the virtual machine, what can be  ?

SolveKeyGPU Thread GPU#0: creating kangaroos...
GPUEngine: SetParams: Failed to copy to constant memory: invalid device symbol
GPUEngine: Kernel: no kernel image is available for execution on the device
SolveKeyGPU Thread GPU#0: 2^21.32 kangaroos [33.9s]
GPUEngine: Kernel: no kernel image is available for execution on the device

**Comment by JeanLucPons** [comment]
Hi,
On linux ?
What is your ccap ?
Could you execute kanagaroo -l

**Comment by g00dwin555** [comment]
ubuntu 18.04 x64
ccap= 30 and 50 and 40 test
-l it,s ok. determines the correct video card

**Comment by g00dwin555** [comment]
fixed
works
