### ISSUE TITLE
Lots of dead kangaroos

### ISSUE THREAD

**Issue by daedalus** [JeanLucPons/Kangaroo#45]
Hi,

Is this normal?, i'm runing in server mode with 4 clients.

![Screenshot from 2020-06-06 00-00-08](https://user-images.githubusercontent.com/115175/83934634-c2929a80-a788-11ea-915f-a41507b0b428.png)

How can I reduce the number of dead kagaroos?

**Comment by JeanLucPons** [comment]
Hi,
Seems you are searching a key which not in the range or that you have a very large DP overhead.
2^28.83/2^21.05, you have almost 256 times more than expected DP to solve the key.

**Comment by daedalus** [comment]
Hi,
I used the Dp suggested by the application and is 12.
The key is in the 2**63 - 2**64 range.

Do you suggest to try with a smaller dp?

**Comment by djarumlights** [comment]
256 is the end though, innit?

**Comment by daedalus** [comment]
hi, I corrected my last message.

**Comment by daedalus** [comment]
I tried with smaller dps and I get the same results.
Lots of dead kangaroos

**Comment by daedalus** [comment]
bad public key, i'm closing.
