### ISSUE TITLE
Low speed with GTX1070

### ISSUE THREAD

**Issue by Coinpiet** [JeanLucPons/Kangaroo#5]
Hello i have a mining rig with 3 GTX 1070 and 3 nvidia P104 
i compiled code with cuda 10.0

here is my command with 1 card

Kangaroo.exe -t 0 -g 128,256 -gpu -gpuId 1 in.txt
Kangaroo v1.2
Start:49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5E0000000000000000
Stop :49DCCFD96DC5DF56487436F5A1B18C4F5D34F65DDB48CB5EFFFFFFFFFFFFFFFF
Keys :16
Number of CPU thread: 0
Range width: 2^64
Number of random walk: 2^22.00 (Max DP=8)
DP size: 8 [0xFF00000000000000]
GPU: GPU #1 P104-100 (15x128 cores) Grid(128x256) (393.0 MB used)
SolveKeyGPU Thread GPU#1: creating kangaroos...
SolveKeyGPU Thread GPU#1: 2^22.00 kangaroos in 175088.1ms
[9.80 MKey/s][GPU 9.80 MKey/s][Count 2^29.64][Dead 0][01:35][255.3MB]

and here is command with all cards

Kangaroo.exe -t 4 -gpu -gpuId 0,1,2,3,4,5 in.txt
Kangaroo v1.2
Start:25FEEE926526B0B4F0085358DF14702F7F6F04E8EC2200000000000000000000
Stop :25FEEE926526B0B4F0085358DF14702F7F6F04E8EC22FFFFFFFFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 4
Range width: 2^80
Number of random walk: 2^22.49 (Max DP=15)
DP size: 15 [0xFFFE000000000000]
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
SolveKeyCPU Thread 2: 1024 kangaroos
GPU: GPU #0 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#0: creating kangaroos...
GPU: GPU #1 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#1: creating kangaroos...
GPU: GPU #2 P104-100 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#2: creating kangaroos...
GPU: GPU #4 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#4: creating kangaroos...
GPU: GPU #3 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
GPU: GPU #5 GeForce GTX 1070 (15x128 cores) Grid(30x256) (99.0 MB used)
SolveKeyGPU Thread GPU#5: creating kangaroos...
SolveKeyGPU Thread GPU#3: creating kangaroos...
SolveKeyGPU Thread GPU#0: 2^19.91 kangaroos in 275949.1ms
SolveKeyGPU Thread GPU#2: 2^19.91 kangaroos in 274457.6ms
SolveKeyGPU Thread GPU#1: 2^19.91 kangaroos in 274979.0ms
SolveKeyGPU Thread GPU#4: 2^19.91 kangaroos in 275555.0ms
SolveKeyGPU Thread GPU#3: 2^19.91 kangaroos in 275891.8ms
SolveKeyGPU Thread GPU#5: 2^19.91 kangaroos in 276465.1ms
[57.85 MKey/s][GPU 56.81 MKey/s][Count 2^33.09][Dead 0][03:03][28.0MB]<

my question is why is it so slow when you get with 1 GTX 1050TI 125 Mkeys per card ?

**Comment by JeanLucPons** [comment]
try remove cpu thread with -t 0

**Comment by JeanLucPons** [comment]
The creation of kangaroos is quite slow.
You cpu seems overloaded.

**Comment by Coinpiet** [comment]
same result with -t 0

**Comment by Coinpiet** [comment]
i have celeron cpu for my mining rig

**Comment by virus-cyber** [comment]
buy brains and do not worry

**Comment by virus-cyber** [comment]
Kangaroo.exe -t 0 -g 28,512 -gpu -gpuId 0 in.txt

**Comment by virus-cyber** [comment]
everyone wants someone else’s bitkonts but no one wants to think

**Comment by Coinpiet** [comment]
same result only get 10 mkeys

**Comment by virus-cyber** [comment]
Kangaroo.exe -t 0 -d 12 -g 28,512 -gpu -gpuId 0 in.txt

**Comment by JeanLucPons** [comment]
If you have compiled by yourself, did you compile as Release version and not Debug.
Debug will be terribly slow.
Creation of 2^20 kangaroos should take 2 ou 3 sec max.

**Comment by Coinpiet** [comment]
ok i download from release and and run Kangaroo.sln in visual studio 
and in Debug folder i get the Kangaroo exe

**Comment by Coinpiet** [comment]
ok i get it now i get 260 Mkeys per card

**Comment by Shadow145-cpu** [comment]
> ok i get it now i get 260 Mkeys per card

How did you fix your speed problem?
