### ISSUE TITLE
PUBKEY ERROR

### ISSUE THREAD

**Issue by sc20099** [JeanLucPons/Kangaroo#58]
MY PUBKEY PREFIX  7...
BUT KANGAROO IS ASKING FOR PREFIX 02, 03 04 

WHAT SHALL I DO

**Comment by DvR4** [comment]
SEC defines three types: 0x00 = point at infinity, 0x02 and 0x03 = compressed, 0x04 = uncompressed
02 basically means even y-point, 03 means odd y-point
