### ISSUE TITLE
Opencl version ?

### ISSUE THREAD

**Issue by RB61** [JeanLucPons/Kangaroo#7]
Any project in sight for  amd gpu type? Thanks.

**Comment by JeanLucPons** [comment]
Hi,
May be if i find time and help from openCl specialist.

**Comment by RB61** [comment]
I willing to give it a try with some guidance. The framework seems to be ready (brichard19/BitCrack). The necessary basic functions are ready (clMath/Secp256k1.cl). I use to mine ETH with amd hardware and I have some 30 RX480 gpu's juste sitting there !
Jean-Luc de Grenoble, je suis sûr que c'est de la tarte pour toi ce truc :) ... Prend soin de toi.  
OMG ! En plus tu es de l'esrf ?  suisi moi même physicien.

**Comment by dem10** [comment]
maybe brichard agrees to help? He is a good programmer on OpenSSLhard agrees to help? He is a good programmer on OpenСL

**Comment by JeanLucPons** [comment]
Hello RB61 ;)
J'hallucine que des gens de l'ESRF se retrouve sur ce post lol
Le monde est petit !

Yes I will try to do something with OpenCl.

**Comment by RB61** [comment]
Hi
Je ne suis pas de l'ESRF mais j'ai travaillé dans le temps sur les particules élementaires en collaboration avec le CERN. Moi aussi, quand j'ai un peu de temps, je bricole  ici et je suis de près ce qui se passe par rapport au puzzle sur bitcointalk (racminer).

Thank you for the very significant contributions you've made here :)

**Comment by dem10** [comment]
> Hello RB61 ;)
> J'hallucine que des gens de l'ESRF se retrouve sur ce post lol
> Le monde est petit !
> 
> Yes I will try to do something with OpenCl.

There are programs that can convert the Cuda code to OpenCL.Yes?No?

**Comment by JeanLucPons** [comment]
The CUDA code is well optimized for 256bits modular arithmetic using 64 bit native arithmetic, OpenCL does not provide 64bit native integer (at least when I looked at a year ago) and native addition with carry. This is a problem...

**Comment by dem10** [comment]
I understand you, JeanLuc. Brichard is a wayward person, although he knows OpenСl very well. Although there is little left to turn the Cuda code into OpenCL.

**Comment by RB61** [comment]
> > Hello RB61 ;)
> > J'hallucine que des gens de l'ESRF se retrouve sur ce post lol
> > Le monde est petit !
> > Yes I will try to do something with OpenCl.
> 
> There are programs that can convert the Cuda code to OpenCL.Yes?No?

Yes
there seem to be a serious project here : https://github.com/vtsynergy/CU2CL
[martinez2011.pdf](https://github.com/JeanLucPons/Kangaroo/files/4533208/martinez2011.pdf)

**Comment by virus-cyber** [comment]
enough to get a person if you have 40 video cards this does not mean that he should give up everything and do for you

**Comment by RB61** [comment]
> enough to get a person if you have 40 video cards this does not mean that he should give up everything and do for you

???

@dem10 asked a question and I simply answered it ...

**Comment by RB61** [comment]
@JeanLucPons  I've found this project which is 6 years old : https://github.com/hhanh00/secp256k1-cl
with little documentation. It seems to be a good start. What do you think?

**Comment by DvR4** [comment]
There is an application written in C # using OpenCL and Cloo to use the GPU. This is not quite what need, but it can come in handy as a starting point for AMD cards.
https://github.com/twjvdhorst/Parallel-Pollard-Rho

**Comment by JeanLucPons** [comment]
Andrew is working on it
Thanks to him ;)
