### ISSUE TITLE
JeanLucPons

### ISSUE THREAD

**Issue by virus-cyber** [JeanLucPons/Kangaroo#8]
give me the bitcoins if you find )))
everyone here is waiting for this only to find someone else's bitcoins and steal them

**Comment by JeanLucPons** [comment]
lol
I will give you if I find but I'm not searching ;)
I'm especially interested in understanding algorithms and technology.
This tool cannot solve a full range, more dedicated to help in some puzzle game...

**Comment by Coinpiet** [comment]
this tool is only interestinmg for people who want like to solve the 110 bit puzzel and higher but higher is more difficullt

**Comment by JeanLucPons** [comment]
yes ;)

**Comment by virus-cyber** [comment]
Are you sure everyone wants to solve puzzle 32? everyone just wants to cheat on Kangaroo as more than once they have not been cheated

**Comment by Coinpiet** [comment]
in my opinion i am sure i only use kangaroo for puzzel

**Comment by hamnaz** [comment]
Jeanluc reminder for multipubkeys version :)

**Comment by JeanLucPons** [comment]
It will be interesting to see if this puzzle32 will evolve with this new tool :D
Hope to have return if someone found something.
I cannot fight with my low cost hardware :)
Yes I keep in mind the multiple key search..

**Comment by hamnaz** [comment]
thankx

**Comment by Coinpiet** [comment]
oh jean luc you get i really big thank you from all of us you have done great and very very special  work :)

**Comment by RB61** [comment]
Very impressive and flawless work 

Tried on Ubuntu 16.04 gcc 7.5 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz  
Kangaroo v1.3
Start:7FFFFFFFFFFFFF
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 8
Range width: 2^56
Number of random walk: 2^13.00 (Max DP=13)
DP size: 13 [0xfff8000000000000]
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 4: 1024 kangaroos
SolveKeyCPU Thread 7: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
SolveKeyCPU Thread 6: 1024 kangaroos
SolveKeyCPU Thread 5: 1024 kangaroos
SolveKeyCPU Thread 2: 1024 kangaroos
[18.42 MKey/s][GPU 0.00 MKey/s][Count 2^29.26][Dead 2][40s][12.0MB]  
[18.42 MKey/s][GPU 0.00 MKey/s][Count 2^29.33][Dead 2][42s][12.4MB]  
Key# 0 Pub:  0x033F2DB2074E3217B3E5EE305301EEEBB1160C4FA1E993EE280112F6348637999A 
Priv: 0x9D18B63AC4FFDF 

Done: Total time 42s 


Tried on Centos 7 gcc 7.3 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz 
case 56
Start:7FFFFFFFFFFFFF
Stop :FFFFFFFFFFFFFF
Keys :1
Number of CPU thread: 12
Range width: 2^56
Number of random walk: 2^13.58 (Max DP=12)
DP size: 12 [0xfff0000000000000]
SolveKeyCPU Thread 0: 1024 kangaroos
SolveKeyCPU Thread 7: 1024 kangaroos
SolveKeyCPU Thread 3: 1024 kangaroos
SolveKeyCPU Thread 5: 1024 kangaroos
SolveKeyCPU Thread 11: 1024 kangaroos
SolveKeyCPU Thread 9: 1024 kangaroos
SolveKeyCPU Thread 6: 1024 kangaroos
SolveKeyCPU Thread 1: 1024 kangaroos
SolveKeyCPU Thread 2: 1024 kangaroos
SolveKeyCPU Thread 4: 1024 kangaroos
SolveKeyCPU Thread 10: 1024 kangaroos
SolveKeyCPU Thread 8: 1024 kangaroos
[35.66 MKey/s][GPU 0.00 MKey/s][Count 2^27.10][Dead 0][06s][6.7MB]  
Key# 0 Pub:  0x033F2DB2074E3217B3E5EE305301EEEBB1160C4FA1E993EE280112F6348637999A 
Priv: 0x9D18B63AC4FFDF 

Done: Total time 06s 

Can't try gpu for now ... have only amd cards at hand :)

**Comment by kpot87** [comment]
> Very impressive and flawless work
> 
> Tried on Ubuntu 16.04 gcc 7.5 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
> Kangaroo v1.3
> Start:7FFFFFFFFFFFFF
> Stop :FFFFFFFFFFFFFF
> Keys :1
> Number of CPU thread: 8
> Range width: 2^56
> Number of random walk: 2^13.00 (Max DP=13)
> DP size: 13 [0xfff8000000000000]
> SolveKeyCPU Thread 1: 1024 kangaroos
> SolveKeyCPU Thread 0: 1024 kangaroos
> SolveKeyCPU Thread 4: 1024 kangaroos
> SolveKeyCPU Thread 7: 1024 kangaroos
> SolveKeyCPU Thread 3: 1024 kangaroos
> SolveKeyCPU Thread 6: 1024 kangaroos
> SolveKeyCPU Thread 5: 1024 kangaroos
> SolveKeyCPU Thread 2: 1024 kangaroos
> [18.42 MKey/s][GPU 0.00 MKey/s][Count 2^29.26][Dead 2][40s][12.0MB]
> [18.42 MKey/s][GPU 0.00 MKey/s][Count 2^29.33][Dead 2][42s][12.4MB]
> Key# 0 Pub: 0x033F2DB2074E3217B3E5EE305301EEEBB1160C4FA1E993EE280112F6348637999A
> Priv: 0x9D18B63AC4FFDF
> 
> Done: Total time 42s
> 
> Tried on Centos 7 gcc 7.3 Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
> case 56
> Start:7FFFFFFFFFFFFF
> Stop :FFFFFFFFFFFFFF
> Keys :1
> Number of CPU thread: 12
> Range width: 2^56
> Number of random walk: 2^13.58 (Max DP=12)
> DP size: 12 [0xfff0000000000000]
> SolveKeyCPU Thread 0: 1024 kangaroos
> SolveKeyCPU Thread 7: 1024 kangaroos
> SolveKeyCPU Thread 3: 1024 kangaroos
> SolveKeyCPU Thread 5: 1024 kangaroos
> SolveKeyCPU Thread 11: 1024 kangaroos
> SolveKeyCPU Thread 9: 1024 kangaroos
> SolveKeyCPU Thread 6: 1024 kangaroos
> SolveKeyCPU Thread 1: 1024 kangaroos
> SolveKeyCPU Thread 2: 1024 kangaroos
> SolveKeyCPU Thread 4: 1024 kangaroos
> SolveKeyCPU Thread 10: 1024 kangaroos
> SolveKeyCPU Thread 8: 1024 kangaroos
> [35.66 MKey/s][GPU 0.00 MKey/s][Count 2^27.10][Dead 0][06s][6.7MB]
> Key# 0 Pub: 0x033F2DB2074E3217B3E5EE305301EEEBB1160C4FA1E993EE280112F6348637999A
> Priv: 0x9D18B63AC4FFDF
> 
> Done: Total time 06s
> 
> Can't try gpu for now ... have only amd cards at hand :)

Almost the same speed of Xenon and Ryze7 (a little bit more)
