### ISSUE TITLE
A 100 with ubuntu 20.04 not working.......solution please....

### ISSUE THREAD

**Issue by siupune** [JeanLucPons/Kangaroo#81]
A 100 PCIE not working with kangaoo in Ubuntu 20.04 (VM).....please suggest a solution.
PUEngine: Kernel: no kernel image is available for execution on the device
GPUEngine: Kernel: no kernel image is available for execution on the device
GPUEngine: Kernel: no kernel image is available for execution on the device
GPUEngine: Kernel: no kernel image is available for execution on the device
![A 100 original kangaroo testing  failed as same resultsJPG](https://user-images.githubusercontent.com/72907883/114668075-ee25d000-9d1d-11eb-9f6b-9e507d5eedc2.JPG)

**Comment by AndreyBobrov** [comment]
This error means you specified the wrong ccap when compiling

**Comment by siupune** [comment]
Do you know what ccap should be there?

**Comment by AndreyBobrov** [comment]
> Do you know what ccap should be there?

According to the [table](https://developer.nvidia.com/cuda-gpus), A100 has compute capability of 8.0. So you have to compile with ccap=80

**Comment by siupune** [comment]
done i did it thanks....
